server:
  port: 8081

spring:
  application:
    name: spring-security-demo
  security:
    user:
      name: dhanushka
      password: abc@123
  datasource:
    url: jdbc:postgresql://localhost:5432/dhanu
    username: postgres
    password: root
